@App.MinimalApi_HostAddress = http://localhost:5160

POST {{App.MinimalApi_HostAddress}}/api/reservation
Content-Type: application/json
Accept: application/json

{
  "Tren": {
    "Ad": "string",
    "Vagonlar": [
      {
        "Ad": "Test",
        "Kapasite": 100,
        "DoluKoltukAdet": 20
      }
    ]
  },
  "RezervasyonYapilacakKisiSayisi": 10,
  "KisilerFarkliVagonlaraYerlestirilebilir": true
}